Repository projectcaluma/ember-caluma, pull requests merged in 2024-08, with the labels that each got.

#2768 fix: pin ember-cli-addon-docs to specific commit until new release
  packages/-ember-caluma/package.json
  pnpm-lock.yaml
Labels: dependencies

#2782 fix(docs): fix build of docs app
  packages/-ember-caluma/config/ember-intl.js
Labels: bug, docs

#2781 fix(form): make sure questions hidden by the widget are really hidden
  packages/form/addon/components/cf-field.hbs
  packages/form/addon/components/cf-field.js
Labels: bug, form rendering

#2780 fix(form): fix table display value of dynamic multiple choice questions
  packages/form/addon/components/cf-field-value.hbs
Labels: bug, form rendering

#2769 chore(deps): update dependencies
  package.json
  packages/-ember-caluma/config/ember-cli-update.json
  packages/-ember-caluma/package.json
  packages/analytics/package.json
  packages/analytics/tests/dummy/config/ember-cli-update.json
  packages/core/package.json
  packages/core/tests/dummy/config/ember-cli-update.json
  packages/distribution/addon/components/cd-inquiry-dialog.js
  packages/distribution/addon/services/distribution.js
  packages/distribution/package.json
  packages/distribution/tests/dummy/config/ember-cli-update.json
  packages/form-builder/package.json
  packages/form-builder/tests/dummy/config/ember-cli-update.json
  packages/form/addon/components/cf-field/input/files.js
  packages/form/package.json
  packages/form/tests/dummy/config/ember-cli-update.json
  packages/testing/package.json
  packages/testing/tests/dummy/config/ember-cli-update.json
  packages/workflow/package.json
  packages/workflow/tests/dummy/config/ember-cli-update.json
  pnpm-lock.yaml
Labels: dependencies
